--
-- Tables
-- This file declares all tables in the public schema.
--

-- Extensions
create extension if not exists "http" with schema "extensions";
create extension if not exists "citext" with schema "extensions";

-- Private schema (used by sales policies migration)
create schema if not exists "private";

create table public.companies (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    name text not null,
    sector text,
    size smallint,
    linkedin_url text,
    website extensions.citext,
    phone_number text,
    address text,
    zipcode text,
    city text,
    state_abbr text,
    sales_id bigint,
    context_links json,
    country text,
    description text,
    revenue text,
    tax_identifier text,
    logo jsonb,
    archived_at timestamp with time zone
);

create table public.contacts (
    id bigint generated by default as identity primary key,
    first_name text,
    last_name text,
    gender text,
    title text,
    background text,
    avatar jsonb,
    first_seen timestamp with time zone,
    last_seen timestamp with time zone,
    has_newsletter boolean,
    status text,
    tags bigint[],
    company_id bigint,
    sales_id bigint,
    linkedin_url text,
    email_jsonb jsonb,
    phone_jsonb jsonb,
    archived_at timestamp with time zone
);

create table public.contact_notes (
    id bigint generated by default as identity (sequence name public."contactNotes_id_seq") not null,
    contact_id bigint not null,
    text text,
    date timestamp with time zone default now(),
    sales_id bigint,
    status text,
    attachments jsonb[]
);

create table public.deals (
    id bigint generated by default as identity primary key,
    name text not null,
    company_id bigint,
    contact_ids bigint[],
    category text,
    stage text not null,
    description text,
    amount numeric(14, 2),
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    archived_at timestamp with time zone,
    expected_closing_date date,
    sales_id bigint,
    index smallint,
    lead_source text,
    client_type text not null default 'new',
    next_follow_up_at timestamp with time zone,
    new_commission_rate_snapshot numeric(5, 2) not null,
    recurring_commission_rate_snapshot numeric(5, 2) not null,
    constraint deals_client_type_check check (client_type in ('new', 'recurring'))
);

create table public.deal_notes (
    id bigint generated by default as identity (sequence name public."dealNotes_id_seq") not null,
    deal_id bigint not null,
    type text,
    text text,
    date timestamp with time zone default now(),
    sales_id bigint,
    attachments jsonb[]
);

create table public.sales (
    id bigint generated by default as identity primary key,
    first_name text not null default 'Pending'::text,
    last_name text not null default 'Pending'::text,
    email extensions.citext not null,
    administrator boolean not null,
    user_id uuid not null,
    avatar jsonb,
    disabled boolean not null default false,
    new_client_commission_rate numeric(5, 2) not null default 20.00,
    recurring_client_commission_rate numeric(5, 2) not null default 15.00,
    constraint sales_new_client_commission_rate_check check (new_client_commission_rate between 0 and 100),
    constraint sales_recurring_client_commission_rate_check check (recurring_client_commission_rate between 0 and 100)
);

create unique index uq__sales__user_id on public.sales using btree (user_id);

create table public.tags (
    id bigint generated by default as identity primary key,
    name text not null,
    color text not null
);

create table public.tasks (
    id bigint generated by default as identity primary key,
    contact_id bigint not null,
    type text,
    text text,
    due_date timestamp with time zone,
    done_date timestamp with time zone,
    sales_id bigint
);

create table public.commissions (
    id bigint generated by default as identity primary key,
    deal_id bigint not null,
    sales_id bigint not null,
    confirmed_client_type text not null,
    final_invoice_total numeric(14, 2) not null,
    applied_rate numeric(5, 2) not null,
    commission_amount numeric(14, 2) not null,
    prior_settled_amount numeric(14, 2) not null default 0,
    balance_amount numeric(14, 2) generated always as (commission_amount - prior_settled_amount) stored,
    first_payment_amount numeric(14, 2) not null,
    first_payment_received_at timestamp with time zone not null,
    first_payment_reference text,
    status text not null default 'pending_review',
    scheduled_for date,
    paid_at timestamp with time zone,
    payout_reference text,
    internal_note text,
    reason text,
    replacement_for_id bigint,
    created_by bigint not null,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint commissions_client_type_check check (confirmed_client_type in ('new', 'recurring')),
    constraint commissions_status_check check (status in ('pending_review', 'approved', 'scheduled', 'paid', 'rejected', 'reversed')),
    constraint commissions_invoice_total_check check (final_invoice_total > 0),
    constraint commissions_first_payment_amount_check check (first_payment_amount > 0),
    constraint commissions_applied_rate_check check (applied_rate between 0 and 100)
);

create unique index commissions_one_active_per_deal_idx
    on public.commissions (deal_id)
    where status not in ('rejected', 'reversed');

create table public.commission_events (
    id bigint generated by default as identity primary key,
    commission_id bigint not null,
    actor_sales_id bigint not null,
    event_type text not null,
    previous_status text,
    new_status text,
    reason text,
    details jsonb not null default '{}'::jsonb,
    created_at timestamp with time zone not null default now()
);

create table public.sales_commission_rate_history (
    id bigint generated by default as identity primary key,
    sales_id bigint not null,
    actor_sales_id bigint not null,
    previous_new_rate numeric(5, 2),
    new_new_rate numeric(5, 2) not null,
    previous_recurring_rate numeric(5, 2),
    new_recurring_rate numeric(5, 2) not null,
    created_at timestamp with time zone not null default now()
);

create table public.deal_ownership_events (
    id bigint generated by default as identity primary key,
    deal_id bigint not null,
    previous_sales_id bigint,
    new_sales_id bigint not null,
    actor_sales_id bigint not null,
    reason text not null,
    created_at timestamp with time zone not null default now()
);

create table public.configuration (
    id integer not null default 1 primary key,
    config jsonb not null default '{}'::jsonb,
    constraint configuration_singleton check (id = 1)
);

create table public.favicons_excluded_domains (
    id bigint generated by default as identity primary key,
    domain text not null
);

--
-- Foreign keys
--

alter table public.companies
    add constraint companies_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.contacts
    add constraint contacts_company_id_fkey foreign key (company_id) references public.companies(id) on update cascade on delete cascade;

alter table public.contacts
    add constraint contacts_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.contact_notes
    add constraint "contactNotes_contact_id_fkey" foreign key (contact_id) references public.contacts(id) on update cascade on delete cascade;

alter table public.contact_notes
    add constraint "contactNotes_sales_id_fkey" foreign key (sales_id) references public.sales(id) on update cascade on delete cascade;

alter table public.deals
    add constraint deals_company_id_fkey foreign key (company_id) references public.companies(id) on update cascade on delete cascade;

alter table public.deals
    add constraint deals_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.deal_notes
    add constraint "dealNotes_deal_id_fkey" foreign key (deal_id) references public.deals(id) on update cascade on delete cascade;

alter table public.deal_notes
    add constraint "dealNotes_sales_id_fkey" foreign key (sales_id) references public.sales(id);

alter table public.sales
    add constraint sales_user_id_fkey foreign key (user_id) references auth.users(id);

alter table public.tasks
    add constraint tasks_contact_id_fkey foreign key (contact_id) references public.contacts(id) on update cascade on delete cascade;

alter table public.commissions
    add constraint commissions_deal_id_fkey foreign key (deal_id) references public.deals(id);

alter table public.commissions
    add constraint commissions_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.commissions
    add constraint commissions_created_by_fkey foreign key (created_by) references public.sales(id);

alter table public.commissions
    add constraint commissions_replacement_for_id_fkey foreign key (replacement_for_id) references public.commissions(id);

alter table public.commission_events
    add constraint commission_events_commission_id_fkey foreign key (commission_id) references public.commissions(id);

alter table public.commission_events
    add constraint commission_events_actor_sales_id_fkey foreign key (actor_sales_id) references public.sales(id);

alter table public.sales_commission_rate_history
    add constraint sales_commission_rate_history_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.sales_commission_rate_history
    add constraint sales_commission_rate_history_actor_sales_id_fkey foreign key (actor_sales_id) references public.sales(id);

alter table public.deal_ownership_events
    add constraint deal_ownership_events_deal_id_fkey foreign key (deal_id) references public.deals(id);

alter table public.deal_ownership_events
    add constraint deal_ownership_events_previous_sales_id_fkey foreign key (previous_sales_id) references public.sales(id);

alter table public.deal_ownership_events
    add constraint deal_ownership_events_new_sales_id_fkey foreign key (new_sales_id) references public.sales(id);

alter table public.deal_ownership_events
    add constraint deal_ownership_events_actor_sales_id_fkey foreign key (actor_sales_id) references public.sales(id);

-- Legacy primary key constraint names (from before snake_case rename)
alter table only public.contact_notes
    add constraint "contactNotes_pkey" primary key (id);

alter table only public.deal_notes
    add constraint "dealNotes_pkey" primary key (id);

--
-- Indexes on foreign keys
--

create index contact_notes_contact_id_idx on public.contact_notes using btree (contact_id);
create index contacts_company_id_idx on public.contacts using btree (company_id);
create index deal_notes_deal_id_idx on public.deal_notes using btree (deal_id);
create index deals_company_id_idx on public.deals using btree (company_id);
create index commissions_sales_id_idx on public.commissions using btree (sales_id);
create index commissions_status_idx on public.commissions using btree (status);
create index commission_events_commission_id_idx on public.commission_events using btree (commission_id);
create index sales_commission_rate_history_sales_id_idx on public.sales_commission_rate_history using btree (sales_id);
create index deal_ownership_events_deal_id_idx on public.deal_ownership_events using btree (deal_id);
