alter table "public"."commission_events" drop constraint "commission_events_actor_sales_id_fkey";

alter table "public"."commissions" drop constraint "commissions_created_by_fkey";

alter table "public"."commissions" drop constraint "commissions_sales_id_fkey";

alter table "public"."contact_notes" drop constraint "contactNotes_sales_id_fkey";

alter table "public"."deal_ownership_events" drop constraint "deal_ownership_events_actor_sales_id_fkey";

alter table "public"."deal_ownership_events" drop constraint "deal_ownership_events_new_sales_id_fkey";

alter table "public"."deal_ownership_events" drop constraint "deal_ownership_events_previous_sales_id_fkey";

alter table "public"."sales" drop constraint "sales_user_id_fkey";

alter table "public"."sales_commission_rate_history" drop constraint "sales_commission_rate_history_actor_sales_id_fkey";

alter table "public"."sales_commission_rate_history" drop constraint "sales_commission_rate_history_sales_id_fkey";

drop view if exists "public"."activity_log";

drop view if exists "public"."companies_summary";


  create table "public"."attachment_namespaces" (
    "namespace_sales_id" bigint not null,
    "current_owner_sales_id" bigint not null,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."attachment_namespaces" enable row level security;


  create table "public"."sales_identities" (
    "id" bigint not null,
    "first_name" text not null,
    "last_name" text not null,
    "email" extensions.citext not null,
    "deleted_at" timestamp with time zone
      );


alter table "public"."sales_identities" enable row level security;


  create table "public"."user_deletion_events" (
    "id" bigint generated by default as identity not null,
    "source_sales_id" bigint not null,
    "replacement_sales_id" bigint not null,
    "actor_sales_id" bigint not null,
    "status" text not null default 'prepared'::text,
    "transfer_counts" jsonb not null default '{}'::jsonb,
    "origin" text not null default 'crm'::text,
    "created_at" timestamp with time zone not null default now(),
    "completed_at" timestamp with time zone
      );


alter table "public"."user_deletion_events" enable row level security;

alter table "public"."companies" add column "created_by_sales_id" bigint;

alter table "public"."contact_notes" add column "created_by_sales_id" bigint;

alter table "public"."contacts" add column "created_by_sales_id" bigint;

alter table "public"."deal_notes" add column "created_by_sales_id" bigint;

alter table "public"."deals" add column "created_by_sales_id" bigint;

alter table "public"."sales" add column "deletion_pending_at" timestamp with time zone;

alter table "public"."sales" add column "deletion_replacement_sales_id" bigint;

alter table "public"."tasks" add column "created_by_sales_id" bigint;

CREATE INDEX attachment_namespaces_current_owner_sales_id_idx ON public.attachment_namespaces USING btree (current_owner_sales_id);

CREATE UNIQUE INDEX attachment_namespaces_pkey ON public.attachment_namespaces USING btree (namespace_sales_id);

CREATE UNIQUE INDEX sales_identities_pkey ON public.sales_identities USING btree (id);

CREATE UNIQUE INDEX user_deletion_events_pkey ON public.user_deletion_events USING btree (id);

CREATE INDEX user_deletion_events_source_sales_id_idx ON public.user_deletion_events USING btree (source_sales_id);

alter table "public"."attachment_namespaces" add constraint "attachment_namespaces_pkey" PRIMARY KEY using index "attachment_namespaces_pkey";

alter table "public"."sales_identities" add constraint "sales_identities_pkey" PRIMARY KEY using index "sales_identities_pkey";

alter table "public"."user_deletion_events" add constraint "user_deletion_events_pkey" PRIMARY KEY using index "user_deletion_events_pkey";

-- Backfill durable identity snapshots before repointing audit foreign keys.
insert into public.sales_identities (id, first_name, last_name, email)
select id, first_name, last_name, email from public.sales;

insert into public.attachment_namespaces (namespace_sales_id, current_owner_sales_id)
select id, id from public.sales;

-- Existing owner columns are the best available creator attribution for rows
-- created before creator snapshots were introduced.
update public.companies set created_by_sales_id = sales_id;
update public.contacts set created_by_sales_id = sales_id;
update public.contact_notes set created_by_sales_id = sales_id;
update public.deals set created_by_sales_id = sales_id;
update public.deal_notes set created_by_sales_id = sales_id;
update public.tasks set created_by_sales_id = sales_id;

do $$
begin
  if exists (
    select 1 from public.companies where created_by_sales_id is null
    union all select 1 from public.contacts where created_by_sales_id is null
    union all select 1 from public.contact_notes where created_by_sales_id is null
    union all select 1 from public.deals where created_by_sales_id is null
    union all select 1 from public.deal_notes where created_by_sales_id is null
    union all select 1 from public.tasks where created_by_sales_id is null
  ) then
    raise exception 'Cannot preserve creator attribution because an existing CRM row has no sales owner';
  end if;
end;
$$;

alter table public.companies alter column created_by_sales_id set not null;
alter table public.contacts alter column created_by_sales_id set not null;
alter table public.contact_notes alter column created_by_sales_id set not null;
alter table public.deals alter column created_by_sales_id set not null;
alter table public.deal_notes alter column created_by_sales_id set not null;
alter table public.tasks alter column created_by_sales_id set not null;

alter table "public"."attachment_namespaces" add constraint "attachment_namespaces_current_owner_sales_id_fkey" FOREIGN KEY (current_owner_sales_id) REFERENCES public.sales(id) ON DELETE CASCADE not valid;

alter table "public"."attachment_namespaces" validate constraint "attachment_namespaces_current_owner_sales_id_fkey";

alter table "public"."attachment_namespaces" add constraint "attachment_namespaces_namespace_sales_id_fkey" FOREIGN KEY (namespace_sales_id) REFERENCES public.sales_identities(id) not valid;

alter table "public"."attachment_namespaces" validate constraint "attachment_namespaces_namespace_sales_id_fkey";

alter table "public"."companies" add constraint "companies_created_by_sales_id_fkey" FOREIGN KEY (created_by_sales_id) REFERENCES public.sales_identities(id) not valid;

alter table "public"."companies" validate constraint "companies_created_by_sales_id_fkey";

alter table "public"."contact_notes" add constraint "contact_notes_created_by_sales_id_fkey" FOREIGN KEY (created_by_sales_id) REFERENCES public.sales_identities(id) not valid;

alter table "public"."contact_notes" validate constraint "contact_notes_created_by_sales_id_fkey";

alter table "public"."contacts" add constraint "contacts_created_by_sales_id_fkey" FOREIGN KEY (created_by_sales_id) REFERENCES public.sales_identities(id) not valid;

alter table "public"."contacts" validate constraint "contacts_created_by_sales_id_fkey";

alter table "public"."deal_notes" add constraint "deal_notes_created_by_sales_id_fkey" FOREIGN KEY (created_by_sales_id) REFERENCES public.sales_identities(id) not valid;

alter table "public"."deal_notes" validate constraint "deal_notes_created_by_sales_id_fkey";

alter table "public"."deals" add constraint "deals_created_by_sales_id_fkey" FOREIGN KEY (created_by_sales_id) REFERENCES public.sales_identities(id) not valid;

alter table "public"."deals" validate constraint "deals_created_by_sales_id_fkey";

alter table "public"."sales" add constraint "sales_deletion_replacement_sales_id_fkey" FOREIGN KEY (deletion_replacement_sales_id) REFERENCES public.sales(id) not valid;

alter table "public"."sales" validate constraint "sales_deletion_replacement_sales_id_fkey";

alter table "public"."tasks" add constraint "tasks_created_by_sales_id_fkey" FOREIGN KEY (created_by_sales_id) REFERENCES public.sales_identities(id) not valid;

alter table "public"."tasks" validate constraint "tasks_created_by_sales_id_fkey";

alter table "public"."tasks" add constraint "tasks_sales_id_fkey" FOREIGN KEY (sales_id) REFERENCES public.sales(id) not valid;

alter table "public"."tasks" validate constraint "tasks_sales_id_fkey";

alter table "public"."user_deletion_events" add constraint "user_deletion_events_actor_sales_id_fkey" FOREIGN KEY (actor_sales_id) REFERENCES public.sales_identities(id) not valid;

alter table "public"."user_deletion_events" validate constraint "user_deletion_events_actor_sales_id_fkey";

alter table "public"."user_deletion_events" add constraint "user_deletion_events_origin_check" CHECK ((origin = ANY (ARRAY['crm'::text, 'supabase_dashboard'::text]))) not valid;

alter table "public"."user_deletion_events" validate constraint "user_deletion_events_origin_check";

alter table "public"."user_deletion_events" add constraint "user_deletion_events_replacement_sales_id_fkey" FOREIGN KEY (replacement_sales_id) REFERENCES public.sales_identities(id) not valid;

alter table "public"."user_deletion_events" validate constraint "user_deletion_events_replacement_sales_id_fkey";

alter table "public"."user_deletion_events" add constraint "user_deletion_events_source_sales_id_fkey" FOREIGN KEY (source_sales_id) REFERENCES public.sales_identities(id) not valid;

alter table "public"."user_deletion_events" validate constraint "user_deletion_events_source_sales_id_fkey";

alter table "public"."user_deletion_events" add constraint "user_deletion_events_status_check" CHECK ((status = ANY (ARRAY['prepared'::text, 'completed'::text]))) not valid;

alter table "public"."user_deletion_events" validate constraint "user_deletion_events_status_check";

alter table "public"."commission_events" add constraint "commission_events_actor_sales_id_fkey" FOREIGN KEY (actor_sales_id) REFERENCES public.sales_identities(id) not valid;

alter table "public"."commission_events" validate constraint "commission_events_actor_sales_id_fkey";

alter table "public"."commissions" add constraint "commissions_created_by_fkey" FOREIGN KEY (created_by) REFERENCES public.sales_identities(id) not valid;

alter table "public"."commissions" validate constraint "commissions_created_by_fkey";

alter table "public"."commissions" add constraint "commissions_sales_id_fkey" FOREIGN KEY (sales_id) REFERENCES public.sales_identities(id) not valid;

alter table "public"."commissions" validate constraint "commissions_sales_id_fkey";

alter table "public"."contact_notes" add constraint "contactNotes_sales_id_fkey" FOREIGN KEY (sales_id) REFERENCES public.sales(id) ON UPDATE CASCADE not valid;

alter table "public"."contact_notes" validate constraint "contactNotes_sales_id_fkey";

alter table "public"."deal_ownership_events" add constraint "deal_ownership_events_actor_sales_id_fkey" FOREIGN KEY (actor_sales_id) REFERENCES public.sales_identities(id) not valid;

alter table "public"."deal_ownership_events" validate constraint "deal_ownership_events_actor_sales_id_fkey";

alter table "public"."deal_ownership_events" add constraint "deal_ownership_events_new_sales_id_fkey" FOREIGN KEY (new_sales_id) REFERENCES public.sales_identities(id) not valid;

alter table "public"."deal_ownership_events" validate constraint "deal_ownership_events_new_sales_id_fkey";

alter table "public"."deal_ownership_events" add constraint "deal_ownership_events_previous_sales_id_fkey" FOREIGN KEY (previous_sales_id) REFERENCES public.sales_identities(id) not valid;

alter table "public"."deal_ownership_events" validate constraint "deal_ownership_events_previous_sales_id_fkey";

alter table "public"."sales" add constraint "sales_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."sales" validate constraint "sales_user_id_fkey";

alter table "public"."sales_commission_rate_history" add constraint "sales_commission_rate_history_actor_sales_id_fkey" FOREIGN KEY (actor_sales_id) REFERENCES public.sales_identities(id) not valid;

alter table "public"."sales_commission_rate_history" validate constraint "sales_commission_rate_history_actor_sales_id_fkey";

alter table "public"."sales_commission_rate_history" add constraint "sales_commission_rate_history_sales_id_fkey" FOREIGN KEY (sales_id) REFERENCES public.sales_identities(id) not valid;

alter table "public"."sales_commission_rate_history" validate constraint "sales_commission_rate_history_sales_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.ensure_attachment_namespace()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
begin
  insert into public.attachment_namespaces (namespace_sales_id, current_owner_sales_id)
  values (new.id, new.id)
  on conflict (namespace_sales_id) do nothing;
  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.finalize_sales_user_deletion(p_event_id bigint)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
begin
  update public.user_deletion_events
    set status = 'completed', completed_at = now()
    where id = p_event_id and status = 'prepared';
  if not found then
    raise exception 'Pending user deletion event not found';
  end if;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.guard_auth_user_deletion()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  source_sale public.sales%rowtype;
begin
  select * into source_sale from public.sales where user_id = old.id;
  if source_sale.id is null then
    return old;
  end if;

  if source_sale.deletion_pending_at is not null then
    return old;
  end if;

  if source_sale.administrator then
    raise exception 'Administrators must be deleted through Xenora CRM';
  end if;

  if exists (select 1 from public.companies where sales_id = source_sale.id)
    or exists (select 1 from public.contacts where sales_id = source_sale.id)
    or exists (select 1 from public.contact_notes where sales_id = source_sale.id)
    or exists (select 1 from public.deals where sales_id = source_sale.id)
    or exists (select 1 from public.deal_notes where sales_id = source_sale.id)
    or exists (select 1 from public.tasks where sales_id = source_sale.id)
    or exists (
      select 1 from storage.objects o
      where o.owner = old.id
        or o.owner_id = old.id::text
        or (
          o.bucket_id = 'attachments'
          and (storage.foldername(o.name))[1] = source_sale.id::text
        )
    ) then
    raise exception 'This user owns CRM data. Delete them through Xenora CRM to transfer it safely';
  end if;

  return old;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.protect_deal_commission_fields()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
begin
  if current_setting('app.user_deletion_transfer', true) = 'on' then
    return new;
  end if;
  if not public.is_admin() then
    new.sales_id := old.sales_id;
    new.new_commission_rate_snapshot := old.new_commission_rate_snapshot;
    new.recurring_commission_rate_snapshot := old.recurring_commission_rate_snapshot;
  end if;
  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.prepare_sales_user_deletion(p_source_sales_id bigint, p_replacement_sales_id bigint, p_actor_sales_id bigint, p_confirmation_email text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  actor_record public.sales%rowtype;
  source_record public.sales%rowtype;
  replacement_record public.sales%rowtype;
  active_admin_count integer;
  event_id bigint;
  company_count integer := 0;
  contact_count integer := 0;
  contact_note_count integer := 0;
  deal_count integer := 0;
  deal_note_count integer := 0;
  task_count integer := 0;
  commission_count integer := 0;
  namespace_count integer := 0;
  storage_object_count integer := 0;
  counts jsonb;
  transferred_deal_ids bigint[] := array[]::bigint[];
  ownership_mismatches jsonb;
begin
  select * into actor_record
    from public.sales
    where id = p_actor_sales_id
    for update;
  if actor_record.id is null or not actor_record.administrator or actor_record.disabled then
    raise exception 'Only an active administrator can delete users';
  end if;

  select * into source_record
    from public.sales
    where id = p_source_sales_id
    for update;
  if source_record.id is null then
    raise exception 'User not found';
  end if;
  if source_record.id = actor_record.id then
    raise exception 'Administrators cannot delete their own account';
  end if;
  if lower(btrim(source_record.email::text)) is distinct from lower(btrim(p_confirmation_email)) then
    raise exception 'Confirmation email does not match';
  end if;

  select * into replacement_record
    from public.sales
    where id = p_replacement_sales_id
    for update;
  if replacement_record.id is null or replacement_record.disabled then
    raise exception 'Replacement user must be active';
  end if;
  if replacement_record.id = source_record.id then
    raise exception 'Replacement user must be different';
  end if;

  if source_record.administrator then
    select count(*) into active_admin_count
      from public.sales
      where administrator = true and disabled = false;
    if active_admin_count <= 1 then
      raise exception 'The final active administrator cannot be deleted';
    end if;
  end if;

  if source_record.deletion_pending_at is not null then
    if source_record.deletion_replacement_sales_id is distinct from replacement_record.id then
      raise exception 'Deletion is already pending with another replacement user';
    end if;
    select id, transfer_counts into event_id, counts
      from public.user_deletion_events
      where source_sales_id = source_record.id and status = 'prepared'
      order by id desc limit 1;
    return jsonb_build_object(
      'event_id', event_id,
      'auth_user_id', source_record.user_id,
      'source_sales_id', source_record.id,
      'replacement_sales_id', replacement_record.id,
      'transfer_counts', coalesce(counts, '{}'::jsonb),
      'deletion_pending', true
    );
  end if;

  select coalesce(array_agg(id), array[]::bigint[]) into transferred_deal_ids
    from public.deals where sales_id = source_record.id;

  update public.companies set sales_id = replacement_record.id where sales_id = source_record.id;
  get diagnostics company_count = row_count;
  update public.contacts set sales_id = replacement_record.id where sales_id = source_record.id;
  get diagnostics contact_count = row_count;
  perform set_config('app.user_deletion_transfer', 'on', true);
  update public.deals set
    sales_id = replacement_record.id,
    new_commission_rate_snapshot = replacement_record.new_client_commission_rate,
    recurring_commission_rate_snapshot = replacement_record.recurring_client_commission_rate,
    updated_at = now()
  where sales_id = source_record.id;
  get diagnostics deal_count = row_count;
  update public.contact_notes set sales_id = replacement_record.id where sales_id = source_record.id;
  get diagnostics contact_note_count = row_count;
  update public.deal_notes set sales_id = replacement_record.id where sales_id = source_record.id;
  get diagnostics deal_note_count = row_count;
  update public.tasks set sales_id = replacement_record.id where sales_id = source_record.id;
  get diagnostics task_count = row_count;
  update public.commissions
    set
      sales_id = replacement_record.id,
      applied_rate = case confirmed_client_type
        when 'new' then replacement_record.new_client_commission_rate
        else replacement_record.recurring_client_commission_rate
      end,
      commission_amount = round(final_invoice_total * (
        case confirmed_client_type
          when 'new' then replacement_record.new_client_commission_rate
          else replacement_record.recurring_client_commission_rate
        end
      ) / 100, 2),
      updated_at = now()
    where sales_id = source_record.id and status = 'pending_review';
  get diagnostics commission_count = row_count;
  update public.attachment_namespaces
    set current_owner_sales_id = replacement_record.id
    where current_owner_sales_id = source_record.id;
  get diagnostics namespace_count = row_count;
  update storage.objects
    set
      owner = replacement_record.user_id,
      owner_id = replacement_record.user_id::text
    where owner = source_record.user_id
      or owner_id = source_record.user_id::text;
  get diagnostics storage_object_count = row_count;

  perform set_config('app.user_deletion_transfer', 'off', true);
  select jsonb_agg(jsonb_build_object(
    'deal_id', d.id,
    'deal_sales_id', d.sales_id,
    'contact_id', contact_id,
    'contact_sales_id', c.sales_id
  )) into ownership_mismatches
    from public.deals d
    cross join lateral unnest(coalesce(d.contact_ids, array[]::bigint[])) contact_id
    left join public.contacts c on c.id = contact_id
    where d.id = any(transferred_deal_ids)
      and (c.id is null or c.sales_id is distinct from d.sales_id);
  if ownership_mismatches is not null then
    raise exception 'User deletion transfer would leave mismatched deal contact ownership: %', ownership_mismatches;
  end if;

  counts := jsonb_build_object(
    'companies', company_count,
    'contacts', contact_count,
    'contact_notes', contact_note_count,
    'deals', deal_count,
    'deal_notes', deal_note_count,
    'tasks', task_count,
    'pending_commissions', commission_count,
    'attachment_namespaces', namespace_count,
    'storage_objects', storage_object_count
  );

  update public.sales set
    disabled = true,
    deletion_pending_at = now(),
    deletion_replacement_sales_id = replacement_record.id
  where id = source_record.id;

  insert into public.user_deletion_events (
    source_sales_id, replacement_sales_id, actor_sales_id, transfer_counts
  ) values (
    source_record.id, replacement_record.id, actor_record.id, counts
  ) returning id into event_id;

  return jsonb_build_object(
    'event_id', event_id,
    'auth_user_id', source_record.user_id,
    'source_sales_id', source_record.id,
    'replacement_sales_id', replacement_record.id,
    'transfer_counts', counts,
    'deletion_pending', true
  );
end;
$function$
;

CREATE OR REPLACE FUNCTION public.validate_deal_contacts_owner()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
begin
  if current_setting('app.user_deletion_transfer', true) = 'on' then
    return new;
  end if;
  if new.contact_ids is not null and exists (
    select 1
    from unnest(new.contact_ids) contact_id
    left join public.contacts c on c.id = contact_id
    where c.id is null or c.sales_id is distinct from new.sales_id
  ) then
    raise exception 'All deal contacts must belong to the deal owner';
  end if;
  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.set_created_by_sales_id()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
begin
  if new.created_by_sales_id is null then
    new.created_by_sales_id := coalesce(public.current_sales_id(), new.sales_id);
  end if;
  if new.created_by_sales_id is null then
    raise exception 'Unable to resolve record creator';
  end if;
  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.sync_sales_identity()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
begin
  if tg_op = 'DELETE' then
    update public.sales_identities
      set deleted_at = coalesce(deleted_at, now())
      where id = old.id;
    return old;
  end if;

  insert into public.sales_identities (id, first_name, last_name, email, deleted_at)
  values (new.id, new.first_name, new.last_name, new.email, null)
  on conflict (id) do update set
    first_name = excluded.first_name,
    last_name = excluded.last_name,
    email = excluded.email,
    deleted_at = null;
  return new;
end;
$function$
;

create or replace view "public"."activity_log" with (security_invoker = on) as  SELECT (('company.'::text || c.id) || '.created'::text) AS id,
    'company.created'::text AS type,
    c.created_at AS date,
    c.id AS company_id,
    c.created_by_sales_id AS sales_id,
    to_json(c.*) AS company,
    NULL::json AS contact,
    NULL::json AS deal,
    NULL::json AS contact_note,
    NULL::json AS deal_note
   FROM public.companies c
UNION ALL
 SELECT (('contact.'::text || co.id) || '.created'::text) AS id,
    'contact.created'::text AS type,
    co.first_seen AS date,
    co.company_id,
    co.created_by_sales_id AS sales_id,
    NULL::json AS company,
    to_json(co.*) AS contact,
    NULL::json AS deal,
    NULL::json AS contact_note,
    NULL::json AS deal_note
   FROM public.contacts co
UNION ALL
 SELECT (('contactNote.'::text || cn.id) || '.created'::text) AS id,
    'contactNote.created'::text AS type,
    cn.date,
    co.company_id,
    cn.created_by_sales_id AS sales_id,
    NULL::json AS company,
    NULL::json AS contact,
    NULL::json AS deal,
    to_json(cn.*) AS contact_note,
    NULL::json AS deal_note
   FROM (public.contact_notes cn
     LEFT JOIN public.contacts co ON ((co.id = cn.contact_id)))
UNION ALL
 SELECT (('deal.'::text || d.id) || '.created'::text) AS id,
    'deal.created'::text AS type,
    d.created_at AS date,
    d.company_id,
    d.created_by_sales_id AS sales_id,
    NULL::json AS company,
    NULL::json AS contact,
    to_json(d.*) AS deal,
    NULL::json AS contact_note,
    NULL::json AS deal_note
   FROM public.deals d
UNION ALL
 SELECT (('dealNote.'::text || dn.id) || '.created'::text) AS id,
    'dealNote.created'::text AS type,
    dn.date,
    d.company_id,
    dn.created_by_sales_id AS sales_id,
    NULL::json AS company,
    NULL::json AS contact,
    NULL::json AS deal,
    NULL::json AS contact_note,
    to_json(dn.*) AS deal_note
   FROM (public.deal_notes dn
     LEFT JOIN public.deals d ON ((d.id = dn.deal_id)));


create or replace view "public"."companies_summary" with (security_invoker = on) as  SELECT c.id,
    c.created_at,
    c.name,
    c.sector,
    c.size,
    c.linkedin_url,
    c.website,
    c.phone_number,
    c.address,
    c.zipcode,
    c.city,
    c.state_abbr,
    c.sales_id,
    c.context_links,
    c.country,
    c.description,
    c.revenue,
    c.tax_identifier,
    c.logo,
    c.archived_at,
    count(DISTINCT d.id) AS nb_deals,
    count(DISTINCT co.id) AS nb_contacts
   FROM ((public.companies c
     LEFT JOIN public.deals d ON ((c.id = d.company_id)))
     LEFT JOIN public.contacts co ON ((c.id = co.company_id)))
  GROUP BY c.id;


revoke all on table "public"."attachment_namespaces" from "anon";
revoke all on table "public"."attachment_namespaces" from "authenticated";
revoke all on table "public"."attachment_namespaces" from "service_role";
grant select on table "public"."attachment_namespaces" to "authenticated";

grant select on table "public"."attachment_namespaces" to "service_role";

revoke all on table "public"."sales_identities" from "anon";
revoke all on table "public"."sales_identities" from "authenticated";
revoke all on table "public"."sales_identities" from "service_role";
grant select on table "public"."sales_identities" to "authenticated";

grant select on table "public"."sales_identities" to "service_role";

revoke all on table "public"."user_deletion_events" from "anon";
revoke all on table "public"."user_deletion_events" from "authenticated";
revoke all on table "public"."user_deletion_events" from "service_role";
grant select on table "public"."user_deletion_events" to "authenticated";

grant select on table "public"."user_deletion_events" to "service_role";

grant all on table "public"."activity_log" to "anon";
grant all on table "public"."activity_log" to "authenticated";
grant all on table "public"."activity_log" to "service_role";

grant all on table "public"."companies_summary" to "anon";
grant all on table "public"."companies_summary" to "authenticated";
grant all on table "public"."companies_summary" to "service_role";

revoke all on function public.prepare_sales_user_deletion(bigint, bigint, bigint, text) from public;
grant execute on function public.prepare_sales_user_deletion(bigint, bigint, bigint, text) to service_role;
revoke all on function public.finalize_sales_user_deletion(bigint) from public;
grant execute on function public.finalize_sales_user_deletion(bigint) to service_role;
revoke all on function public.sync_sales_identity() from public;
revoke all on function public.ensure_attachment_namespace() from public;
revoke all on function public.guard_auth_user_deletion() from public;


  create policy "Attachment namespaces select own or admin"
  on "public"."attachment_namespaces"
  as permissive
  for select
  to authenticated
using ((public.is_admin() OR (current_owner_sales_id = public.current_sales_id())));



  create policy "Sales identities read authenticated"
  on "public"."sales_identities"
  as permissive
  for select
  to authenticated
using ((public.current_sales_id() IS NOT NULL));



  create policy "User deletion events select admin"
  on "public"."user_deletion_events"
  as permissive
  for select
  to authenticated
using (public.is_admin());


CREATE TRIGGER zz_set_company_created_by_sales_id BEFORE INSERT ON public.companies FOR EACH ROW EXECUTE FUNCTION public.set_created_by_sales_id();

CREATE TRIGGER zz_set_contact_note_created_by_sales_id BEFORE INSERT ON public.contact_notes FOR EACH ROW EXECUTE FUNCTION public.set_created_by_sales_id();

CREATE TRIGGER zz_set_contact_created_by_sales_id BEFORE INSERT ON public.contacts FOR EACH ROW EXECUTE FUNCTION public.set_created_by_sales_id();

CREATE TRIGGER zz_set_deal_note_created_by_sales_id BEFORE INSERT ON public.deal_notes FOR EACH ROW EXECUTE FUNCTION public.set_created_by_sales_id();

CREATE TRIGGER zz_set_deal_created_by_sales_id BEFORE INSERT ON public.deals FOR EACH ROW EXECUTE FUNCTION public.set_created_by_sales_id();

CREATE TRIGGER "10_sync_sales_identity" AFTER INSERT OR DELETE OR UPDATE ON public.sales FOR EACH ROW EXECUTE FUNCTION public.sync_sales_identity();

CREATE TRIGGER "20_ensure_attachment_namespace" AFTER INSERT ON public.sales FOR EACH ROW EXECUTE FUNCTION public.ensure_attachment_namespace();

CREATE TRIGGER zz_set_task_created_by_sales_id BEFORE INSERT ON public.tasks FOR EACH ROW EXECUTE FUNCTION public.set_created_by_sales_id();

CREATE TRIGGER on_auth_user_deleting BEFORE DELETE ON auth.users FOR EACH ROW EXECUTE FUNCTION public.guard_auth_user_deletion();

drop policy "CRM files delete own or admin" on "storage"."objects";

drop policy "CRM files select own or admin" on "storage"."objects";

drop policy "CRM files update own or admin" on "storage"."objects";


  create policy "CRM files delete own or admin"
  on "storage"."objects"
  as permissive
  for delete
  to authenticated
using (((bucket_id = 'attachments'::text) AND (public.is_admin() OR (EXISTS ( SELECT 1
   FROM public.attachment_namespaces namespace
  WHERE (((namespace.namespace_sales_id)::text = (storage.foldername(objects.name))[1]) AND (namespace.current_owner_sales_id = public.current_sales_id())))) OR ((COALESCE(array_length(storage.foldername(name), 1), 0) = 0) AND public.can_access_legacy_attachment(name)))));



  create policy "CRM files select own or admin"
  on "storage"."objects"
  as permissive
  for select
  to authenticated
using (((bucket_id = 'attachments'::text) AND (public.is_admin() OR (EXISTS ( SELECT 1
   FROM public.attachment_namespaces namespace
  WHERE (((namespace.namespace_sales_id)::text = (storage.foldername(objects.name))[1]) AND (namespace.current_owner_sales_id = public.current_sales_id())))) OR ((COALESCE(array_length(storage.foldername(name), 1), 0) = 0) AND public.can_access_legacy_attachment(name)))));



  create policy "CRM files update own or admin"
  on "storage"."objects"
  as permissive
  for update
  to authenticated
using (((bucket_id = 'attachments'::text) AND (public.is_admin() OR (EXISTS ( SELECT 1
   FROM public.attachment_namespaces namespace
  WHERE (((namespace.namespace_sales_id)::text = (storage.foldername(objects.name))[1]) AND (namespace.current_owner_sales_id = public.current_sales_id())))) OR ((COALESCE(array_length(storage.foldername(name), 1), 0) = 0) AND public.can_access_legacy_attachment(name)))));
