drop policy "Company Delete Policy" on "public"."companies";

drop policy "Enable insert for authenticated users only" on "public"."companies";

drop policy "Enable read access for authenticated users" on "public"."companies";

drop policy "Enable update for authenticated users only" on "public"."companies";

drop policy "Enable insert for admins" on "public"."configuration";

drop policy "Enable read for authenticated" on "public"."configuration";

drop policy "Enable update for admins" on "public"."configuration";

drop policy "Contact Notes Delete Policy" on "public"."contact_notes";

drop policy "Contact Notes Update policy" on "public"."contact_notes";

drop policy "Enable insert for authenticated users only" on "public"."contact_notes";

drop policy "Enable read access for authenticated users" on "public"."contact_notes";

drop policy "Contact Delete Policy" on "public"."contacts";

drop policy "Enable insert for authenticated users only" on "public"."contacts";

drop policy "Enable read access for authenticated users" on "public"."contacts";

drop policy "Enable update for authenticated users only" on "public"."contacts";

drop policy "Deal Notes Delete Policy" on "public"."deal_notes";

drop policy "Deal Notes Update Policy" on "public"."deal_notes";

drop policy "Enable insert for authenticated users only" on "public"."deal_notes";

drop policy "Enable read access for authenticated users" on "public"."deal_notes";

drop policy "Deals Delete Policy" on "public"."deals";

drop policy "Enable insert for authenticated users only" on "public"."deals";

drop policy "Enable read access for authenticated users" on "public"."deals";

drop policy "Enable update for authenticated users only" on "public"."deals";

drop policy "Enable access for authenticated users only" on "public"."favicons_excluded_domains";

drop policy "Enable read access for authenticated users" on "public"."sales";

drop policy "Enable delete for authenticated users only" on "public"."tags";

drop policy "Enable insert for authenticated users only" on "public"."tags";

drop policy "Enable read access for authenticated users" on "public"."tags";

drop policy "Enable update for authenticated users only" on "public"."tags";

drop policy "Enable insert for authenticated users only" on "public"."tasks";

drop policy "Enable read access for authenticated users" on "public"."tasks";

drop policy "Task Delete Policy" on "public"."tasks";

drop policy "Task Update Policy" on "public"."tasks";

drop view if exists "public"."activity_log";

drop view if exists "public"."companies_summary";

drop view if exists "public"."contacts_summary";


  create table "public"."commission_events" (
    "id" bigint generated by default as identity not null,
    "commission_id" bigint not null,
    "actor_sales_id" bigint not null,
    "event_type" text not null,
    "previous_status" text,
    "new_status" text,
    "reason" text,
    "details" jsonb not null default '{}'::jsonb,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."commission_events" enable row level security;


  create table "public"."commissions" (
    "id" bigint generated by default as identity not null,
    "deal_id" bigint not null,
    "sales_id" bigint not null,
    "confirmed_client_type" text not null,
    "final_invoice_total" numeric(14,2) not null,
    "applied_rate" numeric(5,2) not null,
    "commission_amount" numeric(14,2) not null,
    "prior_settled_amount" numeric(14,2) not null default 0,
    "balance_amount" numeric(14,2) generated always as ((commission_amount - prior_settled_amount)) stored,
    "first_payment_amount" numeric(14,2) not null,
    "first_payment_received_at" timestamp with time zone not null,
    "first_payment_reference" text,
    "status" text not null default 'pending_review'::text,
    "scheduled_for" date,
    "paid_at" timestamp with time zone,
    "payout_reference" text,
    "internal_note" text,
    "reason" text,
    "replacement_for_id" bigint,
    "created_by" bigint not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
      );


alter table "public"."commissions" enable row level security;


  create table "public"."deal_ownership_events" (
    "id" bigint generated by default as identity not null,
    "deal_id" bigint not null,
    "previous_sales_id" bigint,
    "new_sales_id" bigint not null,
    "actor_sales_id" bigint not null,
    "reason" text not null,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."deal_ownership_events" enable row level security;


  create table "public"."sales_commission_rate_history" (
    "id" bigint generated by default as identity not null,
    "sales_id" bigint not null,
    "actor_sales_id" bigint not null,
    "previous_new_rate" numeric(5,2),
    "new_new_rate" numeric(5,2) not null,
    "previous_recurring_rate" numeric(5,2),
    "new_recurring_rate" numeric(5,2) not null,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."sales_commission_rate_history" enable row level security;

alter table "public"."companies" add column "archived_at" timestamp with time zone;

alter table "public"."contacts" add column "archived_at" timestamp with time zone;

alter table "public"."deals" add column "client_type" text not null default 'new'::text;

alter table "public"."deals" add column "lead_source" text;

alter table "public"."deals" add column "new_commission_rate_snapshot" numeric(5,2);

alter table "public"."deals" add column "next_follow_up_at" timestamp with time zone;

alter table "public"."deals" add column "recurring_commission_rate_snapshot" numeric(5,2);

alter table "public"."deals" alter column "amount" set data type numeric(14,2) using "amount"::numeric(14,2);

alter table "public"."sales" add column "new_client_commission_rate" numeric(5,2) not null default 20.00;

alter table "public"."sales" add column "recurring_client_commission_rate" numeric(5,2) not null default 15.00;

CREATE INDEX commission_events_commission_id_idx ON public.commission_events USING btree (commission_id);

CREATE UNIQUE INDEX commission_events_pkey ON public.commission_events USING btree (id);

CREATE UNIQUE INDEX commissions_one_active_per_deal_idx ON public.commissions USING btree (deal_id) WHERE (status <> ALL (ARRAY['rejected'::text, 'reversed'::text]));

CREATE UNIQUE INDEX commissions_pkey ON public.commissions USING btree (id);

CREATE INDEX commissions_sales_id_idx ON public.commissions USING btree (sales_id);

CREATE INDEX commissions_status_idx ON public.commissions USING btree (status);

CREATE INDEX deal_ownership_events_deal_id_idx ON public.deal_ownership_events USING btree (deal_id);

CREATE UNIQUE INDEX deal_ownership_events_pkey ON public.deal_ownership_events USING btree (id);

CREATE UNIQUE INDEX sales_commission_rate_history_pkey ON public.sales_commission_rate_history USING btree (id);

CREATE INDEX sales_commission_rate_history_sales_id_idx ON public.sales_commission_rate_history USING btree (sales_id);

alter table "public"."commission_events" add constraint "commission_events_pkey" PRIMARY KEY using index "commission_events_pkey";

alter table "public"."commissions" add constraint "commissions_pkey" PRIMARY KEY using index "commissions_pkey";

alter table "public"."deal_ownership_events" add constraint "deal_ownership_events_pkey" PRIMARY KEY using index "deal_ownership_events_pkey";

alter table "public"."sales_commission_rate_history" add constraint "sales_commission_rate_history_pkey" PRIMARY KEY using index "sales_commission_rate_history_pkey";

alter table "public"."commission_events" add constraint "commission_events_actor_sales_id_fkey" FOREIGN KEY (actor_sales_id) REFERENCES public.sales(id) not valid;

alter table "public"."commission_events" validate constraint "commission_events_actor_sales_id_fkey";

alter table "public"."commission_events" add constraint "commission_events_commission_id_fkey" FOREIGN KEY (commission_id) REFERENCES public.commissions(id) not valid;

alter table "public"."commission_events" validate constraint "commission_events_commission_id_fkey";

alter table "public"."commissions" add constraint "commissions_applied_rate_check" CHECK (((applied_rate >= (0)::numeric) AND (applied_rate <= (100)::numeric))) not valid;

alter table "public"."commissions" validate constraint "commissions_applied_rate_check";

alter table "public"."commissions" add constraint "commissions_client_type_check" CHECK ((confirmed_client_type = ANY (ARRAY['new'::text, 'recurring'::text]))) not valid;

alter table "public"."commissions" validate constraint "commissions_client_type_check";

alter table "public"."commissions" add constraint "commissions_created_by_fkey" FOREIGN KEY (created_by) REFERENCES public.sales(id) not valid;

alter table "public"."commissions" validate constraint "commissions_created_by_fkey";

alter table "public"."commissions" add constraint "commissions_deal_id_fkey" FOREIGN KEY (deal_id) REFERENCES public.deals(id) not valid;

alter table "public"."commissions" validate constraint "commissions_deal_id_fkey";

alter table "public"."commissions" add constraint "commissions_first_payment_amount_check" CHECK ((first_payment_amount > (0)::numeric)) not valid;

alter table "public"."commissions" validate constraint "commissions_first_payment_amount_check";

alter table "public"."commissions" add constraint "commissions_invoice_total_check" CHECK ((final_invoice_total > (0)::numeric)) not valid;

alter table "public"."commissions" validate constraint "commissions_invoice_total_check";

alter table "public"."commissions" add constraint "commissions_replacement_for_id_fkey" FOREIGN KEY (replacement_for_id) REFERENCES public.commissions(id) not valid;

alter table "public"."commissions" validate constraint "commissions_replacement_for_id_fkey";

alter table "public"."commissions" add constraint "commissions_sales_id_fkey" FOREIGN KEY (sales_id) REFERENCES public.sales(id) not valid;

alter table "public"."commissions" validate constraint "commissions_sales_id_fkey";

alter table "public"."commissions" add constraint "commissions_status_check" CHECK ((status = ANY (ARRAY['pending_review'::text, 'approved'::text, 'scheduled'::text, 'paid'::text, 'rejected'::text, 'reversed'::text]))) not valid;

alter table "public"."commissions" validate constraint "commissions_status_check";

alter table "public"."deal_ownership_events" add constraint "deal_ownership_events_actor_sales_id_fkey" FOREIGN KEY (actor_sales_id) REFERENCES public.sales(id) not valid;

alter table "public"."deal_ownership_events" validate constraint "deal_ownership_events_actor_sales_id_fkey";

alter table "public"."deal_ownership_events" add constraint "deal_ownership_events_deal_id_fkey" FOREIGN KEY (deal_id) REFERENCES public.deals(id) not valid;

alter table "public"."deal_ownership_events" validate constraint "deal_ownership_events_deal_id_fkey";

alter table "public"."deal_ownership_events" add constraint "deal_ownership_events_new_sales_id_fkey" FOREIGN KEY (new_sales_id) REFERENCES public.sales(id) not valid;

alter table "public"."deal_ownership_events" validate constraint "deal_ownership_events_new_sales_id_fkey";

alter table "public"."deal_ownership_events" add constraint "deal_ownership_events_previous_sales_id_fkey" FOREIGN KEY (previous_sales_id) REFERENCES public.sales(id) not valid;

alter table "public"."deal_ownership_events" validate constraint "deal_ownership_events_previous_sales_id_fkey";

alter table "public"."deals" add constraint "deals_client_type_check" CHECK ((client_type = ANY (ARRAY['new'::text, 'recurring'::text]))) not valid;

alter table "public"."deals" validate constraint "deals_client_type_check";

alter table "public"."sales" add constraint "sales_new_client_commission_rate_check" CHECK (((new_client_commission_rate >= (0)::numeric) AND (new_client_commission_rate <= (100)::numeric))) not valid;

alter table "public"."sales" validate constraint "sales_new_client_commission_rate_check";

alter table "public"."sales" add constraint "sales_recurring_client_commission_rate_check" CHECK (((recurring_client_commission_rate >= (0)::numeric) AND (recurring_client_commission_rate <= (100)::numeric))) not valid;

alter table "public"."sales" validate constraint "sales_recurring_client_commission_rate_check";

alter table "public"."sales_commission_rate_history" add constraint "sales_commission_rate_history_actor_sales_id_fkey" FOREIGN KEY (actor_sales_id) REFERENCES public.sales(id) not valid;

alter table "public"."sales_commission_rate_history" validate constraint "sales_commission_rate_history_actor_sales_id_fkey";

alter table "public"."sales_commission_rate_history" add constraint "sales_commission_rate_history_sales_id_fkey" FOREIGN KEY (sales_id) REFERENCES public.sales(id) not valid;

alter table "public"."sales_commission_rate_history" validate constraint "sales_commission_rate_history_sales_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.current_sales_id()
 RETURNS bigint
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO ''
AS $function$
  select id from public.sales where user_id = auth.uid() limit 1;
$function$
;

CREATE OR REPLACE FUNCTION public.protect_deal_commission_fields()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
begin
  if not public.is_admin() then
    new.sales_id := old.sales_id;
    new.new_commission_rate_snapshot := old.new_commission_rate_snapshot;
    new.recurring_commission_rate_snapshot := old.recurring_commission_rate_snapshot;
  end if;
  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.reassign_deal(deal_id bigint, new_sales_id bigint, reason text)
 RETURNS public.deals
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
#variable_conflict use_variable
declare
  actor_id bigint;
  deal_record public.deals%rowtype;
  new_partner public.sales%rowtype;
  updated_deal public.deals%rowtype;
  pending_commission public.commissions%rowtype;
begin
  if not public.is_admin() then
    raise exception 'Only administrators can reassign deals';
  end if;
  if nullif(reason, '') is null then
    raise exception 'A reassignment reason is required';
  end if;
  actor_id := public.current_sales_id();
  select * into deal_record from public.deals where id = deal_id for update;
  select * into new_partner from public.sales where id = new_sales_id and disabled = false;
  if deal_record.id is null or new_partner.id is null then
    raise exception 'Deal or active partner not found';
  end if;
  if exists (
    select 1 from public.commissions c
    where c.deal_id = deal_record.id and c.status in ('approved', 'scheduled', 'paid')
  ) then
    raise exception 'Reverse the approved commission before reassigning this deal';
  end if;

  update public.deals set
    sales_id = new_partner.id,
    new_commission_rate_snapshot = new_partner.new_client_commission_rate,
    recurring_commission_rate_snapshot = new_partner.recurring_client_commission_rate,
    updated_at = now()
  where id = deal_record.id returning * into updated_deal;

  update public.deal_notes set sales_id = new_partner.id where deal_notes.deal_id = deal_record.id;
  update public.commissions c set
    sales_id = new_partner.id,
    applied_rate = case c.confirmed_client_type
      when 'new' then new_partner.new_client_commission_rate
      else new_partner.recurring_client_commission_rate
    end,
    commission_amount = round(c.final_invoice_total * (
      case c.confirmed_client_type
        when 'new' then new_partner.new_client_commission_rate
        else new_partner.recurring_client_commission_rate
      end
    ) / 100, 2),
    updated_at = now()
  where c.deal_id = deal_record.id and c.status = 'pending_review';

  insert into public.deal_ownership_events (
    deal_id, previous_sales_id, new_sales_id, actor_sales_id, reason
  ) values (
    deal_record.id, deal_record.sales_id, new_partner.id, actor_id, reason
  );
  return updated_deal;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.record_client_payment(deal_id bigint, confirmed_client_type text, final_invoice_total numeric, first_payment_amount numeric, first_payment_received_at timestamp with time zone, first_payment_reference text DEFAULT NULL::text, internal_note text DEFAULT NULL::text)
 RETURNS public.commissions
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
#variable_conflict use_variable
declare
  actor_id bigint;
  deal_record public.deals%rowtype;
  commission_record public.commissions%rowtype;
  applied_rate numeric(5, 2);
begin
  if not public.is_admin() then
    raise exception 'Only administrators can record client payments';
  end if;
  actor_id := public.current_sales_id();

  if confirmed_client_type not in ('new', 'recurring') then
    raise exception 'Invalid client type';
  end if;
  if final_invoice_total <= 0 or first_payment_amount <= 0 then
    raise exception 'Invoice total and first payment must be positive';
  end if;

  select * into deal_record from public.deals where id = deal_id for update;
  if deal_record.id is null then
    raise exception 'Deal not found';
  end if;
  if deal_record.stage <> 'won' then
    raise exception 'Client payment can only be recorded for a won deal';
  end if;

  applied_rate := case confirmed_client_type
    when 'new' then deal_record.new_commission_rate_snapshot
    else deal_record.recurring_commission_rate_snapshot
  end;

  insert into public.commissions (
    deal_id, sales_id, confirmed_client_type, final_invoice_total,
    applied_rate, commission_amount, first_payment_amount,
    first_payment_received_at, first_payment_reference, internal_note, created_by
  ) values (
    deal_record.id, deal_record.sales_id, confirmed_client_type,
    final_invoice_total, applied_rate,
    round(final_invoice_total * applied_rate / 100, 2),
    first_payment_amount, first_payment_received_at,
    nullif(first_payment_reference, ''), nullif(internal_note, ''), actor_id
  ) returning * into commission_record;

  insert into public.commission_events (
    commission_id, actor_sales_id, event_type, new_status, details
  ) values (
    commission_record.id, actor_id, 'created', commission_record.status,
    jsonb_build_object(
      'final_invoice_total', commission_record.final_invoice_total,
      'applied_rate', commission_record.applied_rate,
      'commission_amount', commission_record.commission_amount
    )
  );

  return commission_record;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.replace_commission(commission_id bigint, confirmed_client_type text, final_invoice_total numeric, reason text)
 RETURNS public.commissions
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
#variable_conflict use_variable
declare
  actor_id bigint;
  current_record public.commissions%rowtype;
  deal_record public.deals%rowtype;
  replacement public.commissions%rowtype;
  applied_rate numeric(5, 2);
  settled numeric(14, 2);
begin
  if not public.is_admin() then
    raise exception 'Only administrators can replace commissions';
  end if;
  if nullif(reason, '') is null then
    raise exception 'A replacement reason is required';
  end if;
  if confirmed_client_type not in ('new', 'recurring') or final_invoice_total <= 0 then
    raise exception 'Invalid replacement values';
  end if;
  actor_id := public.current_sales_id();

  select * into current_record from public.commissions where id = commission_id for update;
  if current_record.id is null or current_record.status not in ('approved', 'scheduled', 'paid') then
    raise exception 'Only approved, scheduled, or paid commissions can be replaced';
  end if;
  select * into deal_record from public.deals where id = current_record.deal_id;
  applied_rate := case confirmed_client_type
    when 'new' then deal_record.new_commission_rate_snapshot
    else deal_record.recurring_commission_rate_snapshot
  end;
  settled := current_record.prior_settled_amount +
    case when current_record.status = 'paid' then current_record.balance_amount else 0 end;

  update public.commissions set status = 'reversed', reason = reason, updated_at = now()
    where id = commission_id;
  insert into public.commission_events (
    commission_id, actor_sales_id, event_type, previous_status, new_status, reason
  ) values (
    commission_id, actor_id, 'reversed_for_replacement', current_record.status, 'reversed', reason
  );

  insert into public.commissions (
    deal_id, sales_id, confirmed_client_type, final_invoice_total,
    applied_rate, commission_amount, prior_settled_amount,
    first_payment_amount, first_payment_received_at, first_payment_reference,
    status, internal_note, replacement_for_id, created_by
  ) values (
    current_record.deal_id, current_record.sales_id, confirmed_client_type,
    final_invoice_total, applied_rate,
    round(final_invoice_total * applied_rate / 100, 2), settled,
    current_record.first_payment_amount, current_record.first_payment_received_at,
    current_record.first_payment_reference, 'pending_review', current_record.internal_note,
    current_record.id, actor_id
  ) returning * into replacement;

  insert into public.commission_events (
    commission_id, actor_sales_id, event_type, new_status, reason,
    details
  ) values (
    replacement.id, actor_id, 'replacement_created', replacement.status, reason,
    jsonb_build_object('replaces', current_record.id, 'prior_settled_amount', settled)
  );
  return replacement;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.set_deal_commission_rate_snapshots()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
declare
  partner public.sales%rowtype;
begin
  if new.sales_id is null then
    new.sales_id := public.current_sales_id();
  end if;

  select * into partner from public.sales where id = new.sales_id;
  if partner.id is null then
    raise exception 'Sales partner not found';
  end if;

  new.new_commission_rate_snapshot := partner.new_client_commission_rate;
  new.recurring_commission_rate_snapshot := partner.recurring_client_commission_rate;
  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.transition_commission(commission_id bigint, new_status text, scheduled_for date DEFAULT NULL::date, paid_at timestamp with time zone DEFAULT NULL::timestamp with time zone, payout_reference text DEFAULT NULL::text, reason text DEFAULT NULL::text)
 RETURNS public.commissions
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
#variable_conflict use_variable
declare
  actor_id bigint;
  current_record public.commissions%rowtype;
  updated_record public.commissions%rowtype;
  allowed boolean := false;
begin
  if not public.is_admin() then
    raise exception 'Only administrators can update commissions';
  end if;
  actor_id := public.current_sales_id();

  select * into current_record from public.commissions where id = commission_id for update;
  if current_record.id is null then
    raise exception 'Commission not found';
  end if;

  allowed :=
    (current_record.status = 'pending_review' and new_status in ('approved', 'rejected')) or
    (current_record.status = 'approved' and new_status in ('scheduled', 'paid', 'reversed')) or
    (current_record.status = 'scheduled' and new_status in ('approved', 'paid', 'reversed')) or
    (current_record.status = 'paid' and new_status = 'reversed');
  if not allowed then
    raise exception 'Invalid commission status transition from % to %', current_record.status, new_status;
  end if;
  if new_status = 'scheduled' and scheduled_for is null then
    raise exception 'A scheduled payout date is required';
  end if;
  if new_status = 'paid' and (paid_at is null or nullif(payout_reference, '') is null) then
    raise exception 'Paid date and payout reference are required';
  end if;
  if new_status in ('rejected', 'reversed') and nullif(reason, '') is null then
    raise exception 'A reason is required';
  end if;

  update public.commissions set
    status = new_status,
    scheduled_for = case when new_status = 'scheduled' then scheduled_for else commissions.scheduled_for end,
    paid_at = case when new_status = 'paid' then paid_at else commissions.paid_at end,
    payout_reference = case when new_status = 'paid' then payout_reference else commissions.payout_reference end,
    reason = case when new_status in ('rejected', 'reversed') then reason else commissions.reason end,
    updated_at = now()
  where id = commission_id
  returning * into updated_record;

  insert into public.commission_events (
    commission_id, actor_sales_id, event_type, previous_status, new_status, reason
  ) values (
    commission_id, actor_id, 'status_changed', current_record.status, new_status, nullif(reason, '')
  );
  return updated_record;
end;
$function$
;

create or replace view "public"."activity_log" with (security_invoker=on) as  SELECT (('company.'::text || c.id) || '.created'::text) AS id,
    'company.created'::text AS type,
    c.created_at AS date,
    c.id AS company_id,
    c.sales_id,
    to_json(c.*) AS company,
    NULL::json AS contact,
    NULL::json AS deal,
    NULL::json AS contact_note,
    NULL::json AS deal_note
   FROM public.companies c
UNION ALL
 SELECT (('contact.'::text || co.id) || '.created'::text) AS id,
    'contact.created'::text AS type,
    co.first_seen AS date,
    co.company_id,
    co.sales_id,
    NULL::json AS company,
    to_json(co.*) AS contact,
    NULL::json AS deal,
    NULL::json AS contact_note,
    NULL::json AS deal_note
   FROM public.contacts co
UNION ALL
 SELECT (('contactNote.'::text || cn.id) || '.created'::text) AS id,
    'contactNote.created'::text AS type,
    cn.date,
    co.company_id,
    cn.sales_id,
    NULL::json AS company,
    NULL::json AS contact,
    NULL::json AS deal,
    to_json(cn.*) AS contact_note,
    NULL::json AS deal_note
   FROM (public.contact_notes cn
     LEFT JOIN public.contacts co ON ((co.id = cn.contact_id)))
UNION ALL
 SELECT (('deal.'::text || d.id) || '.created'::text) AS id,
    'deal.created'::text AS type,
    d.created_at AS date,
    d.company_id,
    d.sales_id,
    NULL::json AS company,
    NULL::json AS contact,
    to_json(d.*) AS deal,
    NULL::json AS contact_note,
    NULL::json AS deal_note
   FROM public.deals d
UNION ALL
 SELECT (('dealNote.'::text || dn.id) || '.created'::text) AS id,
    'dealNote.created'::text AS type,
    dn.date,
    d.company_id,
    dn.sales_id,
    NULL::json AS company,
    NULL::json AS contact,
    NULL::json AS deal,
    NULL::json AS contact_note,
    to_json(dn.*) AS deal_note
   FROM (public.deal_notes dn
     LEFT JOIN public.deals d ON ((d.id = dn.deal_id)));


create or replace view "public"."companies_summary" with (security_invoker=on) as  SELECT c.id,
    c.created_at,
    c.name,
    c.sector,
    c.size,
    c.linkedin_url,
    c.website,
    c.phone_number,
    c.address,
    c.zipcode,
    c.city,
    c.state_abbr,
    c.sales_id,
    c.context_links,
    c.country,
    c.description,
    c.revenue,
    c.tax_identifier,
    c.logo,
    c.archived_at,
    count(DISTINCT d.id) AS nb_deals,
    count(DISTINCT co.id) AS nb_contacts
   FROM ((public.companies c
     LEFT JOIN public.deals d ON ((c.id = d.company_id)))
     LEFT JOIN public.contacts co ON ((c.id = co.company_id)))
  GROUP BY c.id;


create or replace view "public"."contacts_summary" with (security_invoker=on) as  SELECT co.id,
    co.first_name,
    co.last_name,
    co.gender,
    co.title,
    co.background,
    co.avatar,
    co.first_seen,
    co.last_seen,
    co.has_newsletter,
    co.status,
    co.tags,
    co.company_id,
    co.sales_id,
    co.linkedin_url,
    co.email_jsonb,
    co.phone_jsonb,
    co.archived_at,
    (jsonb_path_query_array(co.email_jsonb, '$[*]."email"'::jsonpath))::text AS email_fts,
    (jsonb_path_query_array(co.phone_jsonb, '$[*]."number"'::jsonpath))::text AS phone_fts,
    c.name AS company_name,
    count(DISTINCT t.id) FILTER (WHERE (t.done_date IS NULL)) AS nb_tasks
   FROM ((public.contacts co
     LEFT JOIN public.tasks t ON ((co.id = t.contact_id)))
     LEFT JOIN public.companies c ON ((co.company_id = c.id)))
  GROUP BY co.id, c.name;


grant references on table "public"."commission_events" to "anon";

grant trigger on table "public"."commission_events" to "anon";

grant truncate on table "public"."commission_events" to "anon";

grant delete on table "public"."commission_events" to "authenticated";

grant insert on table "public"."commission_events" to "authenticated";

grant references on table "public"."commission_events" to "authenticated";

grant select on table "public"."commission_events" to "authenticated";

grant trigger on table "public"."commission_events" to "authenticated";

grant truncate on table "public"."commission_events" to "authenticated";

grant update on table "public"."commission_events" to "authenticated";

grant delete on table "public"."commission_events" to "service_role";

grant insert on table "public"."commission_events" to "service_role";

grant references on table "public"."commission_events" to "service_role";

grant select on table "public"."commission_events" to "service_role";

grant trigger on table "public"."commission_events" to "service_role";

grant truncate on table "public"."commission_events" to "service_role";

grant update on table "public"."commission_events" to "service_role";

grant references on table "public"."commissions" to "anon";

grant trigger on table "public"."commissions" to "anon";

grant truncate on table "public"."commissions" to "anon";

grant delete on table "public"."commissions" to "authenticated";

grant insert on table "public"."commissions" to "authenticated";

grant references on table "public"."commissions" to "authenticated";

grant select on table "public"."commissions" to "authenticated";

grant trigger on table "public"."commissions" to "authenticated";

grant truncate on table "public"."commissions" to "authenticated";

grant update on table "public"."commissions" to "authenticated";

grant delete on table "public"."commissions" to "service_role";

grant insert on table "public"."commissions" to "service_role";

grant references on table "public"."commissions" to "service_role";

grant select on table "public"."commissions" to "service_role";

grant trigger on table "public"."commissions" to "service_role";

grant truncate on table "public"."commissions" to "service_role";

grant update on table "public"."commissions" to "service_role";

grant delete on table "public"."companies" to "anon";

grant insert on table "public"."companies" to "anon";

grant select on table "public"."companies" to "anon";

grant update on table "public"."companies" to "anon";

grant delete on table "public"."configuration" to "anon";

grant insert on table "public"."configuration" to "anon";

grant select on table "public"."configuration" to "anon";

grant update on table "public"."configuration" to "anon";

grant delete on table "public"."configuration" to "authenticated";

grant delete on table "public"."configuration" to "service_role";

grant delete on table "public"."contact_notes" to "anon";

grant insert on table "public"."contact_notes" to "anon";

grant select on table "public"."contact_notes" to "anon";

grant update on table "public"."contact_notes" to "anon";

grant delete on table "public"."contacts" to "anon";

grant insert on table "public"."contacts" to "anon";

grant select on table "public"."contacts" to "anon";

grant update on table "public"."contacts" to "anon";

grant delete on table "public"."deal_notes" to "anon";

grant insert on table "public"."deal_notes" to "anon";

grant select on table "public"."deal_notes" to "anon";

grant update on table "public"."deal_notes" to "anon";

grant references on table "public"."deal_ownership_events" to "anon";

grant trigger on table "public"."deal_ownership_events" to "anon";

grant truncate on table "public"."deal_ownership_events" to "anon";

grant delete on table "public"."deal_ownership_events" to "authenticated";

grant insert on table "public"."deal_ownership_events" to "authenticated";

grant references on table "public"."deal_ownership_events" to "authenticated";

grant select on table "public"."deal_ownership_events" to "authenticated";

grant trigger on table "public"."deal_ownership_events" to "authenticated";

grant truncate on table "public"."deal_ownership_events" to "authenticated";

grant update on table "public"."deal_ownership_events" to "authenticated";

grant delete on table "public"."deal_ownership_events" to "service_role";

grant insert on table "public"."deal_ownership_events" to "service_role";

grant references on table "public"."deal_ownership_events" to "service_role";

grant select on table "public"."deal_ownership_events" to "service_role";

grant trigger on table "public"."deal_ownership_events" to "service_role";

grant truncate on table "public"."deal_ownership_events" to "service_role";

grant update on table "public"."deal_ownership_events" to "service_role";

grant delete on table "public"."deals" to "anon";

grant insert on table "public"."deals" to "anon";

grant select on table "public"."deals" to "anon";

grant update on table "public"."deals" to "anon";

grant delete on table "public"."favicons_excluded_domains" to "anon";

grant insert on table "public"."favicons_excluded_domains" to "anon";

grant select on table "public"."favicons_excluded_domains" to "anon";

grant update on table "public"."favicons_excluded_domains" to "anon";

grant delete on table "public"."sales" to "anon";

grant insert on table "public"."sales" to "anon";

grant select on table "public"."sales" to "anon";

grant update on table "public"."sales" to "anon";

grant references on table "public"."sales_commission_rate_history" to "anon";

grant trigger on table "public"."sales_commission_rate_history" to "anon";

grant truncate on table "public"."sales_commission_rate_history" to "anon";

grant delete on table "public"."sales_commission_rate_history" to "authenticated";

grant insert on table "public"."sales_commission_rate_history" to "authenticated";

grant references on table "public"."sales_commission_rate_history" to "authenticated";

grant select on table "public"."sales_commission_rate_history" to "authenticated";

grant trigger on table "public"."sales_commission_rate_history" to "authenticated";

grant truncate on table "public"."sales_commission_rate_history" to "authenticated";

grant update on table "public"."sales_commission_rate_history" to "authenticated";

grant delete on table "public"."sales_commission_rate_history" to "service_role";

grant insert on table "public"."sales_commission_rate_history" to "service_role";

grant references on table "public"."sales_commission_rate_history" to "service_role";

grant select on table "public"."sales_commission_rate_history" to "service_role";

grant trigger on table "public"."sales_commission_rate_history" to "service_role";

grant truncate on table "public"."sales_commission_rate_history" to "service_role";

grant update on table "public"."sales_commission_rate_history" to "service_role";

grant delete on table "public"."tags" to "anon";

grant insert on table "public"."tags" to "anon";

grant select on table "public"."tags" to "anon";

grant update on table "public"."tags" to "anon";

grant delete on table "public"."tasks" to "anon";

grant insert on table "public"."tasks" to "anon";

grant select on table "public"."tasks" to "anon";

grant update on table "public"."tasks" to "anon";


  create policy "Commission events select own or admin"
  on "public"."commission_events"
  as permissive
  for select
  to authenticated
using ((public.is_admin() OR (EXISTS ( SELECT 1
   FROM public.commissions c
  WHERE ((c.id = commission_events.commission_id) AND (c.sales_id = public.current_sales_id()))))));



  create policy "Commissions select own or admin"
  on "public"."commissions"
  as permissive
  for select
  to authenticated
using ((public.is_admin() OR (sales_id = public.current_sales_id())));



  create policy "Companies delete admin"
  on "public"."companies"
  as permissive
  for delete
  to authenticated
using (public.is_admin());



  create policy "Companies insert own or admin"
  on "public"."companies"
  as permissive
  for insert
  to authenticated
with check ((public.is_admin() OR (sales_id = public.current_sales_id())));



  create policy "Companies select own or admin"
  on "public"."companies"
  as permissive
  for select
  to authenticated
using ((public.is_admin() OR (sales_id = public.current_sales_id())));



  create policy "Companies update own or admin"
  on "public"."companies"
  as permissive
  for update
  to authenticated
using ((public.is_admin() OR (sales_id = public.current_sales_id())))
with check ((public.is_admin() OR (sales_id = public.current_sales_id())));



  create policy "Configuration insert admin"
  on "public"."configuration"
  as permissive
  for insert
  to authenticated
with check (public.is_admin());



  create policy "Configuration read authenticated"
  on "public"."configuration"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Configuration update admin"
  on "public"."configuration"
  as permissive
  for update
  to authenticated
using (public.is_admin())
with check (public.is_admin());



  create policy "Contact notes delete admin"
  on "public"."contact_notes"
  as permissive
  for delete
  to authenticated
using (public.is_admin());



  create policy "Contact notes insert own or admin"
  on "public"."contact_notes"
  as permissive
  for insert
  to authenticated
with check (((public.is_admin() OR (sales_id = public.current_sales_id())) AND (EXISTS ( SELECT 1
   FROM public.contacts c
  WHERE ((c.id = contact_notes.contact_id) AND (public.is_admin() OR (c.sales_id = public.current_sales_id())))))));



  create policy "Contact notes select own or admin"
  on "public"."contact_notes"
  as permissive
  for select
  to authenticated
using ((public.is_admin() OR (sales_id = public.current_sales_id())));



  create policy "Contact notes update own or admin"
  on "public"."contact_notes"
  as permissive
  for update
  to authenticated
using ((public.is_admin() OR (sales_id = public.current_sales_id())))
with check ((public.is_admin() OR (sales_id = public.current_sales_id())));



  create policy "Contacts delete admin"
  on "public"."contacts"
  as permissive
  for delete
  to authenticated
using (public.is_admin());



  create policy "Contacts insert own or admin"
  on "public"."contacts"
  as permissive
  for insert
  to authenticated
with check (((public.is_admin() OR (sales_id = public.current_sales_id())) AND ((company_id IS NULL) OR (EXISTS ( SELECT 1
   FROM public.companies c
  WHERE ((c.id = contacts.company_id) AND (public.is_admin() OR (c.sales_id = public.current_sales_id()))))))));



  create policy "Contacts select own or admin"
  on "public"."contacts"
  as permissive
  for select
  to authenticated
using ((public.is_admin() OR (sales_id = public.current_sales_id())));



  create policy "Contacts update own or admin"
  on "public"."contacts"
  as permissive
  for update
  to authenticated
using ((public.is_admin() OR (sales_id = public.current_sales_id())))
with check (((public.is_admin() OR (sales_id = public.current_sales_id())) AND ((company_id IS NULL) OR (EXISTS ( SELECT 1
   FROM public.companies c
  WHERE ((c.id = contacts.company_id) AND (public.is_admin() OR (c.sales_id = public.current_sales_id()))))))));



  create policy "Deal notes delete admin"
  on "public"."deal_notes"
  as permissive
  for delete
  to authenticated
using (public.is_admin());



  create policy "Deal notes insert own or admin"
  on "public"."deal_notes"
  as permissive
  for insert
  to authenticated
with check (((public.is_admin() OR (sales_id = public.current_sales_id())) AND (EXISTS ( SELECT 1
   FROM public.deals d
  WHERE ((d.id = deal_notes.deal_id) AND (public.is_admin() OR (d.sales_id = public.current_sales_id())))))));



  create policy "Deal notes select own or admin"
  on "public"."deal_notes"
  as permissive
  for select
  to authenticated
using ((public.is_admin() OR (sales_id = public.current_sales_id())));



  create policy "Deal notes update own or admin"
  on "public"."deal_notes"
  as permissive
  for update
  to authenticated
using ((public.is_admin() OR (sales_id = public.current_sales_id())))
with check ((public.is_admin() OR (sales_id = public.current_sales_id())));



  create policy "Deal ownership events select own or admin"
  on "public"."deal_ownership_events"
  as permissive
  for select
  to authenticated
using ((public.is_admin() OR (previous_sales_id = public.current_sales_id()) OR (new_sales_id = public.current_sales_id())));



  create policy "Deals delete admin"
  on "public"."deals"
  as permissive
  for delete
  to authenticated
using (public.is_admin());



  create policy "Deals insert own or admin"
  on "public"."deals"
  as permissive
  for insert
  to authenticated
with check (((public.is_admin() OR (sales_id = public.current_sales_id())) AND ((company_id IS NULL) OR (EXISTS ( SELECT 1
   FROM public.companies c
  WHERE ((c.id = deals.company_id) AND (public.is_admin() OR (c.sales_id = public.current_sales_id()))))))));



  create policy "Deals select own or admin"
  on "public"."deals"
  as permissive
  for select
  to authenticated
using ((public.is_admin() OR (sales_id = public.current_sales_id())));



  create policy "Deals update own or admin"
  on "public"."deals"
  as permissive
  for update
  to authenticated
using ((public.is_admin() OR (sales_id = public.current_sales_id())))
with check ((public.is_admin() OR (sales_id = public.current_sales_id())));



  create policy "Favicons read authenticated"
  on "public"."favicons_excluded_domains"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Favicons write admin"
  on "public"."favicons_excluded_domains"
  as permissive
  for all
  to authenticated
using (public.is_admin())
with check (public.is_admin());



  create policy "Sales select self or admin"
  on "public"."sales"
  as permissive
  for select
  to authenticated
using ((public.is_admin() OR (user_id = auth.uid())));



  create policy "Rate history select self or admin"
  on "public"."sales_commission_rate_history"
  as permissive
  for select
  to authenticated
using ((public.is_admin() OR (sales_id = public.current_sales_id())));



  create policy "Tags delete admin"
  on "public"."tags"
  as permissive
  for delete
  to authenticated
using (public.is_admin());



  create policy "Tags insert admin"
  on "public"."tags"
  as permissive
  for insert
  to authenticated
with check (public.is_admin());



  create policy "Tags read authenticated"
  on "public"."tags"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Tags update admin"
  on "public"."tags"
  as permissive
  for update
  to authenticated
using (public.is_admin())
with check (public.is_admin());



  create policy "Tasks delete admin"
  on "public"."tasks"
  as permissive
  for delete
  to authenticated
using (public.is_admin());



  create policy "Tasks insert own or admin"
  on "public"."tasks"
  as permissive
  for insert
  to authenticated
with check (((public.is_admin() OR (sales_id = public.current_sales_id())) AND (EXISTS ( SELECT 1
   FROM public.contacts c
  WHERE ((c.id = tasks.contact_id) AND (public.is_admin() OR (c.sales_id = public.current_sales_id())))))));



  create policy "Tasks select own or admin"
  on "public"."tasks"
  as permissive
  for select
  to authenticated
using ((public.is_admin() OR (sales_id = public.current_sales_id())));



  create policy "Tasks update own or admin"
  on "public"."tasks"
  as permissive
  for update
  to authenticated
using ((public.is_admin() OR (sales_id = public.current_sales_id())))
with check ((public.is_admin() OR (sales_id = public.current_sales_id())));


CREATE TRIGGER protect_deal_commission_fields_trigger BEFORE UPDATE ON public.deals FOR EACH ROW EXECUTE FUNCTION public.protect_deal_commission_fields();

CREATE TRIGGER set_deal_commission_rate_snapshots_trigger BEFORE INSERT ON public.deals FOR EACH ROW EXECUTE FUNCTION public.set_deal_commission_rate_snapshots();

insert into storage.buckets (id, name, public)
values ('assets', 'assets', true)
on conflict (id) do update set public = excluded.public;

update storage.buckets set public = false where id = 'attachments';

drop policy "Attachments 1mt4rzk_0" on "storage"."objects";

drop policy "Attachments 1mt4rzk_1" on "storage"."objects";

drop policy "Attachments 1mt4rzk_3" on "storage"."objects";


  create policy "Brand assets read"
  on "storage"."objects"
  as permissive
  for select
  to public
using ((bucket_id = 'assets'::text));



  create policy "Brand assets write admin"
  on "storage"."objects"
  as permissive
  for all
  to authenticated
using (((bucket_id = 'assets'::text) AND public.is_admin()))
with check (((bucket_id = 'assets'::text) AND public.is_admin()));



  create policy "CRM files delete own or admin"
  on "storage"."objects"
  as permissive
  for delete
  to authenticated
using (((bucket_id = 'attachments'::text) AND (public.is_admin() OR ((storage.foldername(name))[1] = (public.current_sales_id())::text))));



  create policy "CRM files insert own or admin"
  on "storage"."objects"
  as permissive
  for insert
  to authenticated
with check (((bucket_id = 'attachments'::text) AND (public.is_admin() OR ((storage.foldername(name))[1] = (public.current_sales_id())::text))));



  create policy "CRM files select own or admin"
  on "storage"."objects"
  as permissive
  for select
  to authenticated
using (((bucket_id = 'attachments'::text) AND (public.is_admin() OR ((storage.foldername(name))[1] = (public.current_sales_id())::text))));



  create policy "CRM files update own or admin"
  on "storage"."objects"
  as permissive
  for update
  to authenticated
using (((bucket_id = 'attachments'::text) AND (public.is_admin() OR ((storage.foldername(name))[1] = (public.current_sales_id())::text))));

